services:
  - type: web
    name: task-tracker-frontend
    env: static
    plan: free
    buildCommand: npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://your-backend-app.onrender.com # Update this with your backend URL
