services:
  - type: web
    name: task-tracker-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://YOUR_BACKEND_URL.onrender.com # Replace with your actual backend URL from Render
