services:
  - type: web
    name: task-tracker-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://suntek.onrender.com/api # Update this with your actual backend URL
